import { Fredoka , Pacifico } from "next/font/google";
import "./globals.css";

const bubblyFont = Fredoka({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-bubbly",
  display: "swap",
});

const cursiveFont = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cursive",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bubblyFont.variable} ${cursiveFont.variable}`}>
      <body>{children}</body>
    </html>
  );
}
